route:
  receiver: spx
  group_by: []
  group_wait: 0s
  group_interval: 1s

receivers:
- name: spx
  webhook_configs:
  - url: ${SPX_TRIGGER_URL}/trigger
    send_resolved: false 
  slack_configs:
  - api_url: ${SLACK_WEBHOOK}
    channel: "#all-alerting"
    send_resolved: false 
    title: "🚨 {{ .CommonLabels.alertname }}"
    text: |
      *Route:* {{ .CommonLabels.route }}
      *Severity:* {{ .CommonLabels.severity }}
      *Summary:* {{ .CommonAnnotations.summary }}
      *Description:* {{ .CommonAnnotations.description }}
      
